workflows:
  android-kivy-build:
    name: Android Kivy Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PYTHON_VERSION: "3.9"
    scripts:
      - name: Check Python environment
        script: |
          if command -v pyenv &> /dev/null; then
            pyenv install -s $PYTHON_VERSION
            pyenv global $PYTHON_VERSION
          else
            echo "pyenv not found. Using system Python."
          fi
          python --version
      - name: Install Python dependencies
        script: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found. Skipping dependency installation."
          fi
      - name: Install Buildozer
        script: |
          pip install buildozer
      - name: Configure Buildozer
        script: |
          if [ -f buildozer.spec ]; then
            buildozer -v android debug
          else
            echo "buildozer.spec not found. Creating a default one."
            buildozer init
            buildozer -v android debug
          fi
    artifacts:
      - bin/*.apk
    
