workflows:
  android-kivy-build:
    name: Android Kivy Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Set Python version and install dependencies
        script: |
          pyenv install -s 3.9
          pyenv global 3.9
          pip install -r requirements.txt
      - name: Install Buildozer
        script: |
          pip install buildozer
      - name: Build Android APK
        script: |
          buildozer -v android debug
    artifacts:
      - bin/*.apk
