workflows:
  android-kivy-build:
    name: Android Kivy Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Check Python environment
        script: |
          if command -v pyenv &> /dev/null; then
            # 根据之前的问题，如果 3.12.7 有 distutils 问题，可换成 3.11 等版本
            pyenv install -s 3.11
            pyenv global 3.11
          else
            echo "pyenv not found. Using system Python."
          fi
          python --version
      - name: Install Python dependencies
        script: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # 安装 Cython
          pip install Cython
      - name: Install Buildozer
        script: |
          pip install buildozer
      - name: Install Android SDK and NDK
        script: |
          brew install android-sdk android-ndk
          export ANDROID_HOME="/usr/local/share/android-sdk"
          export ANDROID_NDK_HOME="/usr/local/share/android-sdk/ndk/25.1.8937393"
          export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
      - name: Configure Buildozer
        script: |
          if [ -f buildozer.spec ]; then
            buildozer -v android debug
          else
            echo "buildozer.spec not found. Creating a default one."
            buildozer init
            buildozer -v android debug
          fi
    artifacts:
      - bin/*.apk
    
